version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/assets"
    target-branch: "develop"
    schedule:
      interval: "monthly"
    cooldown:
      default-days: 5
      semver-major-days: 30
      semver-minor-days: 7
      semver-patch-days: 3

  - package-ecosystem: "mix"
    directory: "/"
    target-branch: "develop"
    schedule:
      interval: "monthly"
    cooldown:
      default-days: 5
      semver-major-days: 30
      semver-minor-days: 7
      semver-patch-days: 3
