name: Staging Deploy

on:
  push:
    branches:
    - test-reusable

jobs:
  build-publish-deploy:
    uses: sigu/shared-actions/.github/workflows/actions.yml@main
    environment: alpha
    with:
      project_name: quadquiz
      service_name: quadquiz
    secrets:
      gce_sa_key: ${{secrets.GCE_SA_KEY}}
      project_id: ${{ secrets.GCE_PROJECT }}
      releases_secrets: ${{ secrets.RELEASES_SECRETS }}
