name: Staging Deploy

on:
  push:
    branches:
      - develop
      - test-staging-deploy

env:
  PROJECT_ID: ${{ secrets.GCE_PROJECT }}

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: "https://staging.quadblockquiz.org/"
    env:
      GCE_INSTANCE: ${{ secrets.GCE_INSTANCE }}
      GCE_INSTANCE_ZONE: us-east4-c
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check if version ends in -dev and branch is valid
        id: check_version
        run: |
          VERSION=$(grep 'version:' mix.exs | sed -E 's/.*version: *"([^"]+)".*/\1/')
          BRANCH="${GITHUB_REF_NAME}"
          echo "Found version: $VERSION on branch: $BRANCH"
          if [[ "$VERSION" == *-dev && ("$BRANCH" == "develop" || "$BRANCH" == "test-staging-deploy") ]]; then
            echo "deploy=true" >> "$GITHUB_OUTPUT"
          else
            echo "deploy=false" >> "$GITHUB_OUTPUT"
          fi

      - id: "auth"
        if: steps.check_version.outputs.deploy == 'true'
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: ${{ secrets.GCE_SA_KEY }}

      - uses: google-github-actions/setup-gcloud@v2
        if: steps.check_version.outputs.deploy == 'true'
        with:
          version: "506.0.0"

      - name: Configure Docker auth
        if: steps.check_version.outputs.deploy == 'true'
        run: gcloud --quiet auth configure-docker

      - name: Build
        if: steps.check_version.outputs.deploy == 'true'
        run: |
          echo '${{ secrets.RELEASES_SECRETS }}' >> config/releases.exs
          echo '${{ secrets.QNA_ANSWERS }}' >> qna/answers.json
          echo '${{ secrets.COURSES_ANSWERS }}' >> courses/answers.json
          docker build --tag "gcr.io/duncan-openc2-plugfest/quadquiz:staging" .

      - name: Publish
        if: steps.check_version.outputs.deploy == 'true'
        run: docker push "gcr.io/duncan-openc2-plugfest/quadquiz:staging"

      - name: Deploy to Cloud Run
        if: steps.check_version.outputs.deploy == 'true'
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: quadquiz-staging
          region: us-east4
          image: "gcr.io/duncan-openc2-plugfest/quadquiz:staging"
